mybatis:
  #mapper文件位置
  mapperLocations: classpath:mapper/*.xml
  #实体类所在的位置，这样在mybatis文件中使用实体类时就不用写完整路径了，只用写类名即可
  typeAliasesPackage: com.example.springredis.domain
spring:
  ####数据源配置
  datasource:
    password: root123
    username: root
    url: jdbc:mysql://192.168.66.141:3306/dbaas?useUnicode=true&characterEncoding=utf-8
  ####redis配置
  redis:
    ###redis服务配置
    host: 8.129.27.199
    #host: 192.168.152.128
    ##redis服务端口
    port: 6379
    ##redis连接密码auth
    password:
    ##jedis数据源设置
    jedis:
      pool:
        max-active: 15
        min-idle: 3
        max-idle: 8
        max-wait: 10s
    database: 0
pagehelper:
  supportMethodsArguments: true
mapper:
  #通用mapper配置文件
  notEmpty: true
  before: true
  style: camelhumpAndLowercase
  enableMethodAnnotation: true
  usePrimitiveType: true
  #安全删除，该属性为true时，delete需要添加上查询条件才能执行，否则报错（使用通用mapper时）
  safeDelete: true
  #安全更新，该属性为true时，update需要添加上查询条件才能执行，否则报错（使用通用mapper时）
  safeUpdate: true
  #是否使用java类型
  useJavaType: true
logging:
  level:
    com.example.springredis.dao: debug



